catalog/urls.py
from django.urls import path

from . import views

app_name='catalog'
urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),

    path(
        'books/',
        views.BookListView.as_view(),
        name='books'
    ),
    path(
        'books/create/',
        views.BookCreate.as_view(),
        name='book-create'
    ),
    path(
        'books/<int:pk>/',
        views.BookDetailView.as_view(),
        name='book-detail'
    ),
    path(
        'books/<int:pk>/update/',
        views.BookUpdate.as_view(),
        name='book-update'
    ),
    path(
        'books/<int:pk>/delete/',
        views.BookDelete.as_view(),
        name='book-delete'
    ),

    path(
        'authors/',
        views.AuthorListView.as_view(),
        name='authors'
    ),
    path(
        'authors/<int:pk>/',
        views.AuthorDetailView.as_view(),
        name='author-detail'
    ),
    path(
        'authors/create/',
        views.AuthorCreate.as_view(),
        name='author-create'
    ),
    path(
        'authors/<int:pk>/update/',
        views.AuthorUpdate.as_view(),
        name='author-update'
    ),
    path(
        'authors/<int:pk>/delete/',
        views.AuthorDelete.as_view(),
        name='author-delete'
    ),

    path(
        'mybooks/',
        views.LoanedBooksByUserListView.as_view(),
        name='my-borrowed'
    ),
    path(
        'borrowed/',
        views.LoanedBooksAllListView.as_view(),
        name='all-borrowed'
    ),

    path(
        'book/<uuid:pk>/renew/',
        views.renew_book_librarian,
        name='renew-book-librarian'
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView, TemplateView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='catalog:index'), name='home'),

    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),

    path('catalog/', include('catalog.urls')),
]

########################################################################
# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
########################################################################

catalog/models.py
import uuid # Required for unique book instances

from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

from datetime import date


class Author(models.Model):
    """
    Model representing an author.
    """
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = [
            'last_name',
            'first_name'
        ]

    def get_absolute_url(self):
        """
        Returns the URL to access a particular author instance.
        """
        return reverse('catalog:author-detail', args=[str(self.id)])

    def __str__(self):
        """
        String for representing the Model object.
        """
        return f'{self.last_name}, {self.first_name}'


class Language(models.Model):
    """
    Model representing a Language (e.g. English, French, Japanese, etc.)
    """
    name = models.CharField(
        max_length=200,
        help_text='Enter the book\'s natural language (e.g. English, French, Japanese etc.)',
    )

    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name


class Genre(models.Model):
    """
    Model representing a book genre.
    """
    name = models.CharField(
        max_length=200,
        help_text='Enter a book genre (e.g. Science Fiction)',
    )

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.name



class Book(models.Model):
    """
    Model representing a book (but not a specific copy of a book).
    """
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author is a string rather than an object because it hasn't been declared yet in the file
    author = models.ForeignKey(
        Author,
        on_delete=models.SET_NULL,
        null=True,
    )
    summary = models.TextField(
        max_length=1000,
        help_text='Enter a brief description of the book',
    )
    isbn = models.CharField(
        'ISBN',
        max_length=13,
        unique=True,
        help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
    )
    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    genre = models.ManyToManyField(
        Genre,
        help_text='Select a genre for this book',
    )
    language = models.ForeignKey(
        Language,
        on_delete=models.SET_NULL,
        null=True,
        help_text='Select a language for this book',
    )

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title

    def get_absolute_url(self):
        """
        Returns the URL to access a detail record for this book.
        """
        return reverse('catalog:book-detail', args=[str(self.id)])

    def display_genre(self):
        """
        Create a string for the Genre. This is required to display genres in `catalog.Book` Admin.
        """
        return ', '.join(genre.name for genre in self.genre.all()[:4])

    display_genre.short_description = 'Genre(s)'



class BookInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed
    from the library).
    """
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text='Unique ID for this particular book across whole library',
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.RESTRICT,
        null=True,
    )
    imprint = models.CharField(max_length=200)
    borrower = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )
    due_back = models.DateField(null=True, blank=True)
    
    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Book availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (('can_mark_returned', 'Set book as returned'),)

    @property
    def is_overdue(self):
        """
        Determines if the book instance is overdue (The user has not returned the book in time).
        """
        return bool(self.due_back and date.today() > self.due_back)

    def __str__(self):
        """
        String for representing the Model object.
        """
        return f'{self.id} ({self.book.title})'

catalog/forms.py
import datetime

from django.forms import Form, DateField
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


class RenewBookForm(Form):
    """
    Form for a librarian to renew books.
    """
    renewal_date = DateField(
        help_text="Enter a date between now and 4 weeks (default 3)."
    )

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past:
        if data < datetime.date.today():
            raise ValidationError(
                _('Invalid date - renewal in past')
            )
        # Check date is in range librarian allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead')
            )

        # Return the cleaned data:
        return data

catalog/views.py
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from catalog.models import Author, Language, Genre, Book, BookInstance
from catalog.forms import RenewBookForm


def index(request):
    """
    View function for home/index page of site.
    """
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(
        status__exact='a',
    ).count()
    num_books_containing_the = Book.objects.filter(
        title__icontains='the'
    ).count()
    num_authors = Author.objects.count()
    num_genres = Genre.objects.count()

    # Get number of visits `num_visits` from the session object. If it doesn't exist, set it to 0.
    num_visits = request.session.get('num_visits', 0)
    # Increment `num_visits` by 1 and then save that new value to `num_visits` in the session object.
    request.session['num_visits'] = num_visits + 1

    context = {
        'num_books': num_books,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_books_containing_the': num_books_containing_the,
        'num_authors': num_authors,
        'num_genres': num_genres,
        'num_visits': num_visits,
    }
    return render(request, 'index.html', context=context)


########################################################################
# Book Views

DEFAULT_BOOK_FIELDS = [
    'title',
    'author',
    'summary',
    'isbn',
    'genre',
    'language',
]

class BookListView(ListView):
    model = Book
    paginate_by = 4

    # def get_queryset(self):
    #     """
    #     Get all the `Book` objects from the database.

    #     This method is not really needed since the default `get_queryset`
    # method will return all books. We're keeping it here for demonstration
    # purposes and a reminder that we could override the default behavior.
    #     """
    #     return Book.objects.all()

    def get_context_data(self, **kwargs):
        """
        Get the context data from the `super` class and add some additional context variable to it.
        """
        # `context` will have both `object_list` and `book_list`, by default, from `super`.
        context = super().get_context_data(**kwargs)
        context['additonal_context_variable'] = 'A sample string here(?)'
        return context


class BookDetailView(DetailView):
    model = Book


class BookCreate(CreateView):
    model = Book
    fields = DEFAULT_BOOK_FIELDS


class BookUpdate(UpdateView):
    model = Book
    fields = DEFAULT_BOOK_FIELDS


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('catalog:books')

########################################################################


########################################################################
# BookInstance Views

class LoanedBooksByUserListView(LoginRequiredMixin, ListView):
    """
    Generic class-based view listing books on loan to current user.
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return BookInstance.objects.filter(
            borrower=self.request.user
        ).filter(
            status__exact='o'
        ).order_by('due_back')


class LoanedBooksAllListView(PermissionRequiredMixin, ListView):
    """
    Generic class-based view listing all books on loan.
    """
    model = BookInstance
    template_name = 'catalog/bookinstance_list_borrowed_all.html'
    paginate_by = 10
    permission_required = 'catalog.can_mark_returned'

    def get_queryset(self):
        return BookInstance.objects.filter(
            status__exact='o'
        ).order_by('due_back')

########################################################################


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_book_librarian(request, pk):
    """
    View function for a Librarian to renew a specific `BookInstance`.
    """
    book_instance = get_object_or_404(BookInstance, pk=pk)

    if request.method == 'POST':
        # Use the `RenewBookForm` to validate the data the user submitted.
        form = RenewBookForm(request.POST)
        # If the user submitted values are valid:
          # No errors in the form:
            # From our `clean_renewal_date`.
            # And any other Django-provided default validation.
        if form.is_valid():
            # "The cleaned data is sanitized, validated, and converted into Python-friendly types."
            book_instance.due_back = form.cleaned_data['renewal_date']
            book_instance.save()

            return HttpResponseRedirect(reverse('catalog:all-borrowed'))

    else:
        proposed_renewal_date = (
            datetime.date.today() + datetime.timedelta(weeks=3)
        )
        form = RenewBookForm(
            initial={'renewal_date': proposed_renewal_date}
        )

    context = {
        'form': form,
        'book_instance': book_instance,
    }

    return render(request, 'catalog/book_renew_librarian.html', context)


########################################################################
# Author Views

class AuthorListView(ListView):
    model = Author
    paginate_by = 10


class AuthorDetailView(DetailView):
    model = Author


class AuthorCreate(PermissionRequiredMixin, CreateView):
    model = Author
    fields = [
        'first_name',
        'last_name',
        'date_of_birth',
        'date_of_death'
    ]
    initial = {'date_of_death': '11/06/2020'}
    permission_required = 'catalog.can_mark_returned'


class AuthorUpdate(UpdateView):
    model = Author
    # fields = '__all__' # Not recommended (potential security issue if
    # more fields added)
    fields = [
        'first_name',
        'last_name',
        'date_of_birth',
        'date_of_death',
    ]


class AuthorDelete(DeleteView):
    model = Author
    success_url = reverse_lazy('catalog:authors')

########################################################################

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}

{% block title %}Author Delete Confirm{% endblock title %}

{% block content %}

	<h1>Delete Author</h1>

	<p>Are you sure you want to delete the author: {{ author }}?</p>

	<form action="" method="POST">
		{% csrf_token %}
		<input type="submit" value="Yes, delete." />
		<button type="button" onclick="location.href='{% url 'catalog:author-detail' author.id %}'">Cancel</button>
	</form>

{% endblock content %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block title %}Author Detail{% endblock title %}

{% block content %}
    <h1>Author</h1>

    <p><strong>Last Name:</strong> {{ author.last_name }}</p>
    <p><strong>First Name:</strong> {{ author.first_name }}</p>
    <p><a href={% url 'catalog:author-update' author.id %}>Edit Author</a></p>
    <p><a href={% url 'catalog:author-delete' author.id %}>Delete Author</a></p>

    <div style="margin-left:20px;margin-top:20px">
        <h2>Books</h2>
        <hr>
        {{ author.book_set.all }}
        {% for book in author.book_set.all %}
            <hr>
            <p><strong>Title:</strong> {{ book.title }}</p>
            <p><strong>Summary:</strong> {{ book.summary }}</p>
            <p><strong>ISBN:</strong> {{ book.isbn }}</p>
            <p><strong>Genre:</strong> {{ book.display_genre }}</p>
            <p><strong>Language:</strong> {{ book.language }}</p>
            <p><strong>Copies:</strong> {{ book.bookinstance_set.count }}</p>
        {% endfor %}
    </div>
{% endblock content %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}

{% block title %}Author Form{% endblock title %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="Submit" />
	</form>
	<button
		type="button"
		onclick="location.href='{% url 'catalog:authors' %}'"
		>
		Cancel
	</button>
{% endblock content %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block title %}Author List{% endblock title %}

{% block content %}
    <h1>Author List</h1>
    <button
        type="button"
        class="btn btn-primary"
        onclick="location.href='{% url 'catalog:author-create' %}'"
        >
        Create New Author
    </button>
    {% if author_list %}
    <ul>
        {% for author in author_list %}
            <li>
                <a
                    href="{{ author.get_absolute_url }}"
                    >
                    {{ author }}
                </a>
            </li>
            <li>
                Number of Titles: {{ author.book_set.count }}
            </li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock content %}

catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block title %}Book Delete Confirm{% endblock title %}

{% block content %}

	<h1>Delete Book</h1>

	<p>Are you sure you want to delete the book: {{ book }}?</p>

	<form action="" method="POST">
		{% csrf_token %}
		<input type="submit" value="Yes, delete." />
		<button type="button" onclick="location.href='{% url 'catalog:book-detail' book.id %}'">Cancel</button>
	</form>

{% endblock content %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block title %}Book Detail{% endblock title %}

{% block content %}
    <h1>Title: {{ book.title }}</h1>

    <p><strong>Author:</strong> <a href="{{ book.author.get_absolute_url }}">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
    <p><strong>Summary:</strong> {{ book.summary }}</p>
    <p><strong>ISBN:</strong> {{ book.isbn }}</p>
    <p><strong>Language:</strong> {{ book.language }}</p>
    <p><strong>Genre:</strong> {{ book.genre.all | join:", " }}</p>

    <button onclick="location.href='{% url 'catalog:book-update' book.id %}'">
        Update "{{ book.title }}"
    </button>
    <button onclick="location.href='{% url 'catalog:book-delete' book.id %}'">
        Delete "{{ book.title }}"
    </button>

    <div style="margin-left:20px;margin-top:20px">
        <h4>Copies</h4>

        {% for copy in book.bookinstance_set.all %}
            <hr>
            <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
                {{ copy.get_status_display }}
            </p>
                {% if copy.status != 'a' %}
                    <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
                {% endif %}
            <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
            <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
        {% endfor %}
    </div>
{% endblock content %}

catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block title %}Book Form{% endblock title %}

{% block content %}
	<form action="" method="post">
		{% csrf_token %}
		<table>
			{{ form.as_table }}
		</table>
		<input type="submit" value="Submit" />
	</form>
	<button
		type="button"
		onclick="location.href='{% url 'catalog:books' %}'"
		>
		Cancel
	</button>
{% endblock content %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block title %}Book List{% endblock title %}

{% block content %}
    <h1>Book List</h1>
    <button
        type="button"
        class="btn btn-primary"
        onclick="location.href='{% url 'catalog:book-create' %}'"
        >
        Create New Book
    </button>
    {% if book_list %}
    <ul>
        {% for book in book_list %}
            <li>
                <a
                    href="{{ book.get_absolute_url }}"
                    >
                    {{ book.title }}
                </a>
                - {{ book.bookinstance_set.count }} copies
                -
                ({{book.author}})
            </li>
        {% endfor %}
    </ul>
    {% else %}
        <p>There are no books in the library.</p>
    {% endif %}
    {{ additonal_context_variable }}
{% endblock content %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block title %}Librarian Renew Loan{% endblock title %}

{% block content %}
    <h1>Renew: {{ book_instance.book.title }}</h1>
    <p>Borrower: {{ book_instance.borrower }}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ book_instance.due_back }}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock content %}

catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block title %}Books Checked Out{% endblock title %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

        {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">
                    {{ bookinst.book.title }}
                </a>
                ({{ bookinst.due_back }})

                - [{{ bookinst.borrower }}]

                {% if perms.catalog.can_mark_returned %}
                    -
                    <a href="{% url 'catalog:renew-book-librarian' bookinst.id %}">
                        Renew
                    </a>
                {% endif %}

            </li>
        {% endfor %}
    </ul>

    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block title %}Your Borrowed Books{% endblock title %}

{% block content %}
    <h1>Borrowed books</h1>

    {% if bookinstance_list %}
    <ul>

        {% for bookinst in bookinstance_list %}
            <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                <a href="{% url 'catalog:book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
            </li>
        {% endfor %}
    </ul>

    {% else %}
        <p>There are no books borrowed.</p>
    {% endif %}
{% endblock %}